### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#138]
- [ ] at the beginning of the 2 game or during the game there is an inability to insert words. There can all bottoms unavailable, or even they may be absent 
![1AF4F68D-5F74-423C-B423-BC1AEEE77D30](https://user-images.githubusercontent.com/63041847/82307146-9f19d280-99c8-11ea-96e8-9b37cf8b09f7.png)
![B4FF52C6-A2BB-4C2E-9413-CD25CE23DD90](https://user-images.githubusercontent.com/63041847/82307129-9a551e80-99c8-11ea-98bb-723ff1a4c39d.png)
- [ ] in the second game when we have 2 similar words, there is inability to highlight one of them
![F13D4727-EDD8-4EFB-89A6-3A1A0AC4AFDA](https://user-images.githubusercontent.com/63041847/82307583-3bdc7000-99c9-11ea-982d-6601d5195e98.jpeg)
- [ ] when we switch to another sentence, the unknown sentence appear for a split second. I couldn’t make screen :(
