### ISSUE TITLE
Tutor correction. Task list.

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#146]
- [x] 1. when the user log out, remove settings. Just remove appearance and language pair 

- [ ] 2.Add black appearance, @annamaksimik help us with design 
 https://www.figma.com/file/wfF6CUdPcukmF8gLJs23vQ/Account-SignIn-SignUp-Settings?node-id=7%3A215
- [ ] 3. align everything like in the pattern below  
https://www.figma.com/file/wfF6CUdPcukmF8gLJs23vQ/Account-SignIn-SignUp-Settings?node-id=3%3A289
- [ ] 4. Change colour in the main menu in the tutor:
there is no similar style for each product, also @annamaksimik help
![image](https://user-images.githubusercontent.com/63041847/83514201-d82f6800-a4db-11ea-868a-4e8774eba913.png)
