### ISSUE TITLE
Task list. 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#200]
Description:
- [ ] Implementing the easiest game in tutor for users, we analyze it and put it in first place among other games.
- [ ]  Make on-boarding to this game 
(Note: Our character appears in the beginning of the game and demonstrates in few words what this game will be about.)
- [ ] Remake top bar in the tutor in the way that it will be shown the sence of the game, like : " Collect the word".
- [ ] Improve one slide instructions in the tutor 
- [ ] Make on-boarding for the tutor
- [ ] Think about some motivations, that y=uyser can get from the games in the tutor 
- [ ] Hints when hovering over the most incomprehensible places
