### ISSUE TITLE
[8h] Create 9 games for testing.  Task list. 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#214]
Description:
- [x] Make progress bar as hearts( if the user win-the quantuty of them is growing)
makes progress in the form of a decreasing number of hearts with incorrect answers, and in case of a victory, a star appears. In addition, please single out the work with these hearts into a separate service method, so that the second Alexander could reuse it. And then there is a plan to change backgrounds (negative and positive) in order to visually show the current state of guessing for the user. At the end of the day, we can completely have a ready-made framework for template games and rivet already 4-5 just by changing the sprites of the hero and the background
- [x] Change backround in the games for negative and positive scripts 
- [x] research of spine-animation:
Starts to develop scenarios for our template games, select a background for the heroes, and do the initial implementation of these games
- [x] Write the scenario for 1 game

**Comment by a-matyukh** [comment]
9 games added to repo:
https://github.com/easably/games/commit/e82d4dbd562834c1390a11720317cef561ba1d2f
https://github.com/easably/games/commit/fc4f49e4fcce22da327936ccbec032e082524043
https://github.com/easably/games/commit/b59ad16f7882c1c02f0e04a3ad8c80617b631906
https://github.com/easably/games/commit/0475137d8eb08df5767e3b3d97ceb3e22e56b278
https://github.com/easably/games/commit/b6c2aae2e04d6223dbd8c4c67e6b5c0b269538da
https://github.com/easably/games/commit/fa489d8991237be7e826d8fbbbff7f635e6dd648
https://github.com/easably/games/commit/cbc580f40d7affc4ac1992fc51a95c3233068f19
https://github.com/easably/games/commit/1ad58ee9ac3296d0d125ad8eaba5c51b33303314
https://github.com/easably/games/commit/9bc99f8d47b5eb9a646f11b2951eaa1f86470f1c

1. Vickey-Puh at London-at-Don

<img width="392" alt="Screen Shot 2020-08-07 at 08 28 44" src="https://user-images.githubusercontent.com/20292939/89633224-3138c500-d8ac-11ea-86cd-424c97fd0905.png">

2. Airoplane go to Berlane

<img width="496" alt="Screen Shot 2020-08-07 at 08 33 21" src="https://user-images.githubusercontent.com/20292939/89633261-3eee4a80-d8ac-11ea-983d-f7353287e8af.png">

3. Mamas go to Bahamas

<img width="497" alt="Screen Shot 2020-08-07 at 08 34 31" src="https://user-images.githubusercontent.com/20292939/89633325-59282880-d8ac-11ea-9132-c71106628ba2.png">

4. Worm Jimmy in Svisloch

<img width="496" alt="Screen Shot 2020-08-07 at 08 35 18" src="https://user-images.githubusercontent.com/20292939/89633463-912f6b80-d8ac-11ea-9805-093304de51f2.png">

5. Adventures of Phrayserovschik in Dzerzhinsk

<img width="498" alt="Screen Shot 2020-08-07 at 08 37 03" src="https://user-images.githubusercontent.com/20292939/89633554-ad330d00-d8ac-11ea-9ca4-075366309e71.png">

6. Reflexing mummy

<img width="498" alt="Screen Shot 2020-08-07 at 08 38 15" src="https://user-images.githubusercontent.com/20292939/89633575-b4f2b180-d8ac-11ea-909d-d55883f0788f.png">

7. Estonian Formula 1

<img width="494" alt="Screen Shot 2020-08-07 at 08 39 57" src="https://user-images.githubusercontent.com/20292939/89633675-de134200-d8ac-11ea-8ce2-0118bf251cf1.png">

8. Rose Elephant need rose garbuzes

<img width="497" alt="Screen Shot 2020-08-07 at 08 42 53" src="https://user-images.githubusercontent.com/20292939/89633715-ee2b2180-d8ac-11ea-8613-c169a8e679e8.png">

9. First Belarussian samandrique

<img width="494" alt="Screen Shot 2020-08-07 at 08 45 25" src="https://user-images.githubusercontent.com/20292939/89633762-fb481080-d8ac-11ea-8b57-6d28ae8f8905.png">

All games coming soon available in our eLang Games Store 🏺
