### ISSUE TITLE
[15h]Bugs report. Task list 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#220]
Description:
- [x] when the user has saved more than 2 words in one sentence, the animation is not shown on the second word.
![image](https://user-images.githubusercontent.com/63041847/91284256-537b7f80-e794-11ea-8ef8-311151643114.png)
Steps to reproduce:
1.Open game "Mummy"
2. Guess the first word (save 2 words from one sentence before that)
3. Make 3 mistakes
4. See there is no animation for the second word 
Expected behavior:
There will be animation for all unknown word
- [x] There is no loading at all
Steps to reproduce:
1. Open game "mummy"
2. Guess the word
3. Tap in "next sentence"
4. Loading is endless
![image](https://user-images.githubusercontent.com/63041847/91284653-ddc3e380-e794-11ea-8b0c-6b562ee4cc61.png)
- [x] After tapping on the "Next sentence" the same sentence is repeat again and again.
![image](https://user-images.githubusercontent.com/63041847/91284808-14016300-e795-11ea-8b23-6fba10ee6b6e.png)
![image](https://user-images.githubusercontent.com/63041847/91284826-195ead80-e795-11ea-85fe-19ed1e34dd18.png)
There is no animation after this at all
- [x] The quantity of lives is endless
Steps to reproduce:
1. Open game "mummy"
2. Tap quickly on the words
3. See that there is the same amount of lives even if you've made a mistakes 
![image](https://user-images.githubusercontent.com/63041847/91285057-63e02a00-e795-11ea-9ced-76254138a688.png)
