### ISSUE TITLE
[26h of 26h🤯]Improvement of the tutor. Task list. Detalization in task ⇓ 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#221]
Time estimate:
- [10h] Hints
- [1h] Congratulation window
- [1h] Remove animation
- [4h] After tapping on "Next sentence" - there is too long loading
- [4h] Incorrect numbering of sentences:
- [3h] When a user choose the game- the word to be guessed should be highlighted automatically
Now user should tap on the word that will be guessed.
- [3h] The animation is loading too long 

Description:
You are to add and improve:
- [x] Improve images quality

- [x] Hints
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=810%3A1489
![image](https://user-images.githubusercontent.com/63041847/91531015-c4e23c00-e914-11ea-8e66-80649621144b.png)

- [x] Congratulation window:
https://www.figma.com/file/biat2pS2aaqXtNGXLxnK3x/Games-Desktop?node-id=801%3A1567
![image](https://user-images.githubusercontent.com/63041847/91530996-bac03d80-e914-11ea-8ce6-88313c29125a.png)-

 - [x] Remove animation or :
![image](https://user-images.githubusercontent.com/63041847/91531320-46d26500-e915-11ea-8227-eaf27aa97856.png)
![image](https://user-images.githubusercontent.com/63041847/91531337-50f46380-e915-11ea-8030-05f3cd09422f.png)
![image](https://user-images.githubusercontent.com/63041847/91531360-58b40800-e915-11ea-8667-7d1958836dfa.png)

 - [x] After tapping on "Next sentence" - there is too long loading
![image](https://user-images.githubusercontent.com/63041847/91531435-77b29a00-e915-11ea-96ec-35b159edd445.png)

- [x] Incorrect numbering of sentences:
![image](https://user-images.githubusercontent.com/63041847/91531585-b3e5fa80-e915-11ea-866e-2cac2edc024d.png)
Tap "Next sentence"
![image](https://user-images.githubusercontent.com/63041847/91531635-c6f8ca80-e915-11ea-8f19-f727bea535ba.png)

- [x] When a user choose the game- the word to be guessed should be highlighted automatically
Now user should tap on the word that will be guessed.
![image](https://user-images.githubusercontent.com/63041847/91531851-1b9c4580-e916-11ea-8626-fd0dbec69171.png)

- [x] The animation is loading too long:
![image](https://user-images.githubusercontent.com/63041847/91531936-3ff82200-e916-11ea-9b2f-a8c67877c7a3.png)
Steps to reproduce:
1. Open tutor
2. Choose the game
3. See that animation is loading too long

- [x] Improve the quality of pictures in the game list
