### ISSUE TITLE
Bug report. Task list

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#235]
- [ ] After clicking on the one letter- another letters(the same) are highlighted:
![image](https://user-images.githubusercontent.com/63041847/91963076-12481a00-ed16-11ea-80c7-770908376cf0.png)

- [ ] the brain overlaps the text
![image](https://user-images.githubusercontent.com/63041847/91962816-bb424500-ed15-11ea-9019-a21bbd05570c.png)

- [ ] the brain is circumcised
![image](https://user-images.githubusercontent.com/63041847/91963428-85ea2700-ed16-11ea-858c-86d7c08aef24.png)

- [ ] before the appearance of the brain, when you click on the hidden word, hints appear, after that, after a few seconds, the brain appears
![image](https://user-images.githubusercontent.com/63041847/91963533-a3b78c00-ed16-11ea-98dd-34d2c3be3025.png)

- [ ] when the sentence passed - the tips did not disappear
![image](https://user-images.githubusercontent.com/63041847/91963819-0f015e00-ed17-11ea-95b5-6da3a30b0ad3.png)

- [ ] after clicking on "translate word" 2 times- happens this...
![image](https://user-images.githubusercontent.com/63041847/91964023-4f60dc00-ed17-11ea-9fbb-d196cfe37dfc.png)

- [ ] After playing with the word several times- tips are displayed randomly.
![image](https://user-images.githubusercontent.com/63041847/91964143-71f2f500-ed17-11ea-9e93-e24168104859.png)

- [ ] guessing the word, the modal window does not appear + the brain appears with prompts
![image](https://user-images.githubusercontent.com/63041847/91964275-9a7aef00-ed17-11ea-9ab9-b6789e22eee6.png)

- [ ] there is no automatic transition to the second word after guessing the first
![image](https://user-images.githubusercontent.com/63041847/91964443-d01fd800-ed17-11ea-9aa0-ef769268f1ff.png) 

- [ ] after clicking on 'next sentence", the game turns over and shows the same game again
![image](https://user-images.githubusercontent.com/63041847/91964595-ff364980-ed17-11ea-8086-2cd23c7a688c.png)

**Comment by EugeneShastak** [comment]
![Снимок экрана 2020-09-28 в 15 03 26](https://user-images.githubusercontent.com/70751961/94430044-f52f2b80-019b-11eb-9008-c102136eb57e.png)

- [ ] Correct big letter My Vocabulary
