### ISSUE TITLE
Correct vocabulary. Task list.

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/context-tutor#245]
Description:
- [ ] Adding a new dictionary only happens once per user
![image](https://user-images.githubusercontent.com/63041847/94516604-d62da980-022e-11eb-9f37-0d1a20d3867f.png)
![image](https://user-images.githubusercontent.com/63041847/94516615-db8af400-022e-11eb-9113-22dc5642f766.png)

- [ ] The colour of translation:
- var(--gray-1-color)

- [ ] buttons (Open, Play, shopping cart) display only when you hover over a word

- [ ] after clicking on Play - switch to a random game with this word

- [ ] deletion of a word occurs only after confirmation "Are you sure you want to delete a word?" A similar modal is used in the player
![image](https://user-images.githubusercontent.com/63041847/94516711-155bfa80-022f-11eb-800f-c55c2cb068b0.png)

- [ ] by clicking on the word card and the "Open" button, the modal word window is displayed
